---
# logging:
#     file_path: "new_project.log"
#     output_verbosity: medium
#     logging_verbosity: debug 

display_config: 
    dimensions: null
    fullscreen: false
    max_dimensions: null
    min_dimensions: null
    multisampling: 1
    title: "Windowing example"
    visibility: true
    vsync: true
    backend: OpenGL